require 'pry'
require 'nokogiri'
require 'open-uri'
require 'launchy'

require_relative '../lib/good_news/scraper'
require_relative '../lib/good_news/topic'
require_relative '../lib/good_news/article'
require_relative '../lib/good_news/cli'
require_relative '../lib/good_news/version'